name: 新增译名
description: 某事物尚无中文译名，提议新增译名。
title: "`Emilia` -> `艾米莉娅`"
labels: ["新增译名"]
body:
  - type: textarea
    id: source
    attributes:
      label: 新译名的来源
    validations:
      required: true
