name: 修改译名
description: 某事物已有中文译名，提议修改译名。
title: "`艾米莉娅` -> `爱蜜莉雅`"
labels: ["修改译名"]
body:
  - type: textarea
    id: source
    attributes:
      label: 新译名的来源
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 为什么新译名比旧译名更好？
    validations:
      required: true
